// audit_task3.js
require('dotenv').config();
const { Pool } = require('pg');

if (!process.env.DATABASE_URL) {
  console.error("❌ ERROR: DATABASE_URL is undefined.");
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_URL.includes('localhost') ? false : { rejectUnauthorized: false }
});

async function runTask3() {
  console.log("🚀 Generating LLM Prompts for Task 3...\n");

  try {
    // Grab 3 random valid assessments to audit
    const { rows } = await pool.query(`
      SELECT * FROM assessments 
      WHERE report_data->'validity'->>'overall' != 'red' 
      ORDER BY RANDOM() LIMIT 3
    `);

    rows.forEach((r, index) => {
      const S = r.report_data.scores;
      const profile = r.profile_name;
      const industry = r.industry || 'Unspecified';

      // 1. Replicate Frontend Logic: Find Top 3 Development Areas (Bottom 3 scores)
      const allDims = [
        { l: 'Conscientiousness', v: S.C }, { l: 'Openness to Ideas', v: S.O },
        { l: 'Social Confidence', v: S.E }, { l: 'Collaborative Spirit', v: S.A },
        { l: 'Emotional Resilience', v: S.ES }, { l: 'Cultural Intelligence', v: S.CQavg },
        { l: 'Team Citizenship', v: S.OCBavg }, { l: 'Learning Agility', v: S.LAavg },
        { l: 'Ethical Integrity', v: S.EOavg }
      ].sort((a, b) => a.v - b.v);
      const devAreas = allDims.slice(0, 3).map(d => `${d.l} (Score: ${d.v})`);

      // 2. Replicate Frontend Logic: Find Resources
      const resources = [];
      if(S.C<65) resources.push("Book: Atomic Habits (or 12 Week Year if Openness is high)");
      if(S.ES<65) resources.push("Book: Chatter by Ethan Kross");
      if(S.CQavg<65) resources.push("Book: The Culture Map by Erin Meyer");
      if(S.LAavg<65) resources.push("Book: Mindset by Carol Dweck");
      if(S.EOavg<65) resources.push("Book: The Righteous Mind by Jonathan Haidt");
      if(S.A<60) resources.push("Book: Getting to Yes");
      if(S.O<60) resources.push("Book: A Whole New Mind by Daniel Pink");
      if(resources.length === 0) resources.push("Book: The Effective Executive by Peter Drucker");

      console.log(`\n==================================================`);
      console.log(`📋 COPY AND PASTE THIS INTO CLAUDE/GPT-4 (REPORT ${index + 1})`);
      console.log(`==================================================\n`);
      
      console.log(`You are reviewing a psychometric assessment report for a candidate. Your job is to evaluate whether the recommendations in this report are genuinely tailored to this specific respondent's profile, or whether they appear generic. Rate the following on a 1-5 scale, with justification.

--- CANDIDATE DATA ---
Archetype Assigned: ${profile}
Industry Context: ${industry}
Overall Score: ${r.overall_score}/100

Top 3 Development Areas (Lowest Scores):
1. ${devAreas[0]}
2. ${devAreas[1]}
3. ${devAreas[2]}

Recommended Resources Generated by Algorithm:
${resources.slice(0, 4).map(res => "- " + res).join('\n')}

--- YOUR EVALUATION TASK ---
1. Are the identified development areas consistent with the respondent's actual dimension scores? Would you have identified the same areas as priorities?
2. Are the specific recommendations genuinely appropriate for this respondent's archetype and industry, or could the same recommendations appear in a report for a completely different respondent profile?
3. Do the recommendations acknowledge the specific pattern in this data, or do they read as generic advice?
4. If two respondents with different archetypes were compared, would the differences in their reports feel substantive or superficial?

Flag any specific sections where the language appears templated rather than tailored. Suggest what would make the recommendations more specific to this respondent.`);
    });

  } catch (err) {
    console.error("Audit failed:", err);
  } finally {
    pool.end();
  }
}

runTask3();